In [1]:
# randomNG = 'Philox'
# randomNG = 'PCG64DXSM'
# randomNG = 'MT19937'
# randomNG = 'SFC64'
import importlib

pass_abc ='xprobRRapril_'

In [2]:
import numpy as np
import time
import datetime
import numba
import concurrent.futures
from math import lgamma, floor
import numpy.random
# bitNG = getattr(numpy.random, randomNG)
from numpy.random import Generator, SeedSequence
from ill_confirm_bias_FNs_03_t0FAST_03cnt_vdisc_explore_prob import confirm_bias_full
np.set_printoptions(suppress=True)



/home/pallavi/python_pallavi_Dtop/confirm_bias_illusory_tuth_002/ill_confirm_bias_FNs_03_t0FAST_03cnt_vdisc_explore_prob.py:42: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def bbpmfNG(vk, vn, va, vb):
/home/pallavi/python_pallavi_Dtop/confirm_bias_illusory_tuth_002/ill_confirm_bias_FNs_03_t0FAST_03cnt_vdisc_explore_prob.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit fo

In [ ]:
# mp.set_start_method("fork")
start = time.perf_counter()

runs = 2000
numarms = 2
maxalphabeta = 4
# numagents = 50
# minagents = 4
# maxagents = 12
pulls = 1000
payprobs = np.asarray([.499, .5])
tollerance = 0
nsteps = 10
timesteps = 10**5

explprob = 0.001 #explore every expltstep many timesteps

mem_depth = [5, 10, 100, 1000]
mem_snap = [10, 100, 1000, 10000] #these values must be multiples of nsteps to get recorded


networktype = 'wheel'
erprobA = 0.5
erprobB = 2-2*(1-erprobA)**.5
print(f'erprobB = {erprobB}')

mem = 100 # must be greater than max numagents. if memshare = 0
memshare = 30 # setting this value and memstore to 0 gives the base model
memstore = 5 # setting this value and memshare to 0 gives the base model
variablediscount = 1

#number of threads
thrds = 10
# numba.set_num_threads(thrds)

for randomNG in ['PCG64DXSM']:
    bitNG = getattr(numpy.random, randomNG)
    for numagents in [12, 15, 25]:
        sg = SeedSequence()
        rgs = [Generator(bitNG(s)) for s in sg.spawn(runs)]
        final_mp = np.zeros((runs, 2))
        depth_mp = np.zeros((runs, len(mem_snap)+1, len(mem_depth)))
        print('*********************************************')
        print('*********************************************')

        inputs = []

        with concurrent.futures.ProcessPoolExecutor(max_workers=thrds) as executor:
            future_to_confirm_bias_full = {executor.submit(confirm_bias_full, explprob, variablediscount, mem_snap, mem_depth, erprobB, mem, memshare, memstore, networktype, maxalphabeta, pulls, numagents, numarms, tollerance, payprobs, nsteps, timesteps, rgs, r): inputs for r in range(runs)}
            for future in concurrent.futures.as_completed(future_to_confirm_bias_full):
                inputs = future_to_confirm_bias_full[future]
                try:
                    data = future.result()
                except Exception as exc:
                    print(f'generated an exception: y? and {exc}')
                else:
                    final_mp[data[3]] = data[0:2]
                    depth_mp[data[3]] = data[2]


        final_mp = np.asarray(final_mp)
        suc_mp = np.asarray(final_mp[:,0])
        con_mp = np.asarray(final_mp[:,1])


        np.save(f'{pass_abc}expl{explprob}{randomNG}vdisc{variablediscount}t0fastNGconsensus_{networktype}_ifer{erprobA}_size{numagents}_t{tollerance}_mem_s_d_{mem}_{memshare}_{memstore}.npy', con_mp)
        np.save(f'{pass_abc}expl{explprob}{randomNG}vdisc{variablediscount}t0fastNGsuccess_{networktype}_ifer{erprobA}_size{numagents}_t{tollerance}_mem_s_d_{mem}_{memshare}_{memstore}.npy', suc_mp)
        np.save(f'{pass_abc}expl{explprob}{randomNG}vdisc{variablediscount}t0fastNGdepths_{networktype}_ifer{erprobA}_size{numagents}_t{tollerance}_mem_s_d_{mem}_{memshare}_{memstore}.npy', depth_mp)

        sucrate = np.sum(suc_mp)/runs
        conrate = np.sum(con_mp)/runs

        depth_mean = np.mean(depth_mp, axis=0)
        depth_std = np.std(depth_mp, axis=0)

        print('time:')
        print(datetime.datetime.now())

        print(f'M memory = {mem} S memshare = {memshare} D memstore = {memstore} discount factor = {variablediscount}')
        print(f'explore probability = {explprob}')
        print(f'for # agents = {numagents} success rate = {sucrate} consensus rate = {conrate}')
        print(f'using {randomNG} generator')
        print('network average memory depths:')
        print(depth_mean)
        print('depths standard deviation')
        print(depth_std)
        print(' ')
        print(' ')

finish = time.perf_counter()
print(f'Finished in {round(finish-start,0)/60} minutes')


erprobB = 0.5857864376269049
*********************************************
*********************************************
time:
2024-04-13 11:24:52.473206
M memory = 100 S memshare = 30 D memstore = 5 discount factor = 1
explore probability = 0.001
for # agents = 12 success rate = 0.7035 consensus rate = 0.991
using PCG64DXSM generator
network average memory depths:
[[1186.3059209  1182.58759075 1117.54094425  631.00476445]
 [   5.178         0.            0.            0.        ]
 [ 200.6895      195.9025        0.            0.        ]
 [1188.5595     1184.874      1119.227         0.        ]
 [1188.845      1185.0355     1120.8905      637.314     ]]
depths standard deviation
[[ 0.26018174  0.27109109  0.7574667   6.18876123]
 [ 7.23486807  0.          0.          0.        ]
 [67.94012136 67.68124551  0.          0.        ]
 [ 8.14772728  9.32223814 23.36870709  0.        ]
 [ 8.08745788  9.43213866 23.2570529  73.13506959]]
 
 
*********************************************
****